name: cargo

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM
        run: sudo apt install llvm-10-dev
      - name: cargo build
        run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM
        run: sudo apt install llvm-10-dev
      - name: cargo test
        run: cargo test --verbose
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM
        run: sudo apt install llvm-10-dev
      - name: cargo bench
        run: cargo bench --verbose
      - name: Upload benchmarks
        uses: actions/upload-artifact@v2
        with:
          name: Benchmarks
          path: ./tutara-interpreter/target/criterion/
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LLVM
        run: sudo apt install llvm-10-dev
      - name: cargo clippy
        run: cargo clippy --verbose
